services:
  - type: web
    name: policy-qa
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: GEMINI_MODEL
        value: gemini-2.0-flash
      - key: EMBED_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: EMBED_DIM
        value: "384"
